all:
  children:
    compute_nodes:
      hosts:
        lci-compute-THISCLUSTER-1:
        lci-compute-THISCLUSTER-2:
    storage_nodes:
      hosts:
        lci-storage-THISCLUSTER-1:
    head_nodes:
      hosts:
        lci-head-THISCLUSTER-1:
          ansible_connection: local
